# BUILDING AND RUNNING: docker compose up -d --build
# ONLY DATABASE: docker compose up -d --build database
# LOGGING: docker logs booking-system-phase4-web -f
# LOGGING: docker logs booking-system-phase4-db -f
# CONNECTING TO CONTAINER: docker exec -it booking-system-phase4-web /bin/sh
# CONNECTING TO CONTAINER: docker exec -it booking-system-phase4-db /bin/sh
# CONNECTING TO DATABASE: docker exec -it booking-system-phase4-db psql -U booking_dbuser -d booking_db
# STOPPING WEB: docker stop booking-system-phase4-web
# REMOVING: docker compose down --volumes
# REMOVING IMAGE (IF NEEDED): docker rmi bs-phase4
name: booking-system-phase4

services:
  database:
    image: postgres:15
    container_name: booking-system-phase4-db
    environment:
      POSTGRES_USER: booking_dbuser
      POSTGRES_PASSWORD: Secret1234!
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - pgroot:/var/lib/postgresql/data

volumes:
  pgroot: {}
